# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.root_api import RootApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRootApi(unittest.TestCase):
    """RootApi unit test stubs"""

    def setUp(self):
        self.api = api.root_api.RootApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_open_api_json(self):
        """Test case for get_open_api_json

        """
        pass

    def test_get_open_api_yaml(self):
        """Test case for get_open_api_yaml

        """
        pass


if __name__ == '__main__':
    unittest.main()
