# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.content_api import ContentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = api.content_api.ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_repo_overrides(self):
        """Test case for list_repo_overrides

        Lists all overrides from repositories specified with the repo option.  # noqa: E501
        """
        pass

    def test_list_repos(self):
        """Test case for list_repos

        Lists all of the repositories that are available to a system.  # noqa: E501
        """
        pass

    def test_update_repo_overrides(self):
        """Test case for update_repo_overrides

        Allows the user to manage custom content repository settings.  # noqa: E501
        """
        pass

    def test_update_repos(self):
        """Test case for update_repos

        Enable or disable repositories.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
