# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.repo import Repo  # noqa: E501
from swagger_client.rest import ApiException


class TestRepo(unittest.TestCase):
    """Repo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepo(self):
        """Test Repo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.repo.Repo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
