# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.environment_api import EnvironmentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEnvironmentApi(unittest.TestCase):
    """EnvironmentApi unit test stubs"""

    def setUp(self):
        self.api = api.environment_api.EnvironmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_environments(self):
        """Test case for list_environments

        Lists all of the environments that have been configured for an organization.  # noqa: E501
        """
        pass

    def test_list_orgs(self):
        """Test case for list_orgs

        Lists all of the organizations which are available to the specified user account.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
