# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.profile_api import ProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self):
        self.api = api.profile_api.ProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_service_level(self):
        """Test case for get_service_level

        Displays the current configured service level preference for products installed on the system.  # noqa: E501
        """
        pass

    def test_list_releases(self):
        """Test case for list_releases

        Lists the available OS versions and the currently set release version (if any).  # noqa: E501
        """
        pass

    def test_set_release(self):
        """Test case for set_release

        Sets a sticky OS version to use when installing or updating packages.  # noqa: E501
        """
        pass

    def test_set_service_level(self):
        """Test case for set_service_level

        Set a service-level preference for this system.  # noqa: E501
        """
        pass

    def test_update_profile(self):
        """Test case for update_profile

        Updates the system information.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
