# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.system_profile import SystemProfile  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemProfile(unittest.TestCase):
    """SystemProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemProfile(self):
        """Test SystemProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.system_profile.SystemProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
