# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.registration_api import RegistrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRegistrationApi(unittest.TestCase):
    """RegistrationApi unit test stubs"""

    def setUp(self):
        self.api = api.registration_api.RegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_regenerate_identity(self):
        """Test case for regenerate_identity

        Requests that the subscription management service issue a new identity certificate for the system, using an existing UUID in the original identity certificate.  # noqa: E501
        """
        pass

    def test_register(self):
        """Test case for register

        Registers a new system to the subscription management service.  # noqa: E501
        """
        pass

    def test_unregister(self):
        """Test case for unregister

        Removes a system's subscriptions and removes it from the subscription management service.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
