# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.subscriptions_api import SubscriptionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = api.subscriptions_api.SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attach(self):
        """Test case for attach

        Attaches one or more subscription pools to the system.  # noqa: E501
        """
        pass

    def test_autoattach(self):
        """Test case for autoattach

        Automatically attaches the best-matched compatible subscription or subscriptions to the system.  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        Displays shows the current status of the products and attached subscriptions for the system.  # noqa: E501
        """
        pass

    def test_list_pool_ids(self):
        """Test case for list_pool_ids

        Lists all of the subscriptions that are compatible with a system.  # noqa: E501
        """
        pass

    def test_list_subscriptions(self):
        """Test case for list_subscriptions

        Lists all of the subscriptions that are compatible with a system.  # noqa: E501
        """
        pass

    def test_redeem(self):
        """Test case for redeem

        Redeems subscription for systems purchased from third-party vendors that include a subscription.  # noqa: E501
        """
        pass

    def test_refresh(self):
        """Test case for refresh

        Pulls the latest subscription data from the server  # noqa: E501
        """
        pass

    def test_remove(self):
        """Test case for remove

        Removes a subscription from the system.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
