# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CandlepinVersion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'server_version': 'str',
        'server_release': 'str',
        'rules_version': 'str'
    }

    attribute_map = {
        'server_version': 'server_version',
        'server_release': 'server_release',
        'rules_version': 'rules_version'
    }

    def __init__(self, server_version=None, server_release=None, rules_version=None):  # noqa: E501
        """CandlepinVersion - a model defined in Swagger"""  # noqa: E501
        self._server_version = None
        self._server_release = None
        self._rules_version = None
        self.discriminator = None
        if server_version is not None:
            self.server_version = server_version
        if server_release is not None:
            self.server_release = server_release
        if rules_version is not None:
            self.rules_version = rules_version

    @property
    def server_version(self):
        """Gets the server_version of this CandlepinVersion.  # noqa: E501


        :return: The server_version of this CandlepinVersion.  # noqa: E501
        :rtype: str
        """
        return self._server_version

    @server_version.setter
    def server_version(self, server_version):
        """Sets the server_version of this CandlepinVersion.


        :param server_version: The server_version of this CandlepinVersion.  # noqa: E501
        :type: str
        """

        self._server_version = server_version

    @property
    def server_release(self):
        """Gets the server_release of this CandlepinVersion.  # noqa: E501


        :return: The server_release of this CandlepinVersion.  # noqa: E501
        :rtype: str
        """
        return self._server_release

    @server_release.setter
    def server_release(self, server_release):
        """Sets the server_release of this CandlepinVersion.


        :param server_release: The server_release of this CandlepinVersion.  # noqa: E501
        :type: str
        """

        self._server_release = server_release

    @property
    def rules_version(self):
        """Gets the rules_version of this CandlepinVersion.  # noqa: E501


        :return: The rules_version of this CandlepinVersion.  # noqa: E501
        :rtype: str
        """
        return self._rules_version

    @rules_version.setter
    def rules_version(self, rules_version):
        """Sets the rules_version of this CandlepinVersion.


        :param rules_version: The rules_version of this CandlepinVersion.  # noqa: E501
        :type: str
        """

        self._rules_version = rules_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CandlepinVersion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CandlepinVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
