# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Consumer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'org_name': 'str',
        'org_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'org_name': 'org_name',
        'org_id': 'org_id'
    }

    def __init__(self, id=None, name=None, org_name=None, org_id=None):  # noqa: E501
        """Consumer - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._org_name = None
        self._org_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if org_name is not None:
            self.org_name = org_name
        if org_id is not None:
            self.org_id = org_id

    @property
    def id(self):
        """Gets the id of this Consumer.  # noqa: E501


        :return: The id of this Consumer.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Consumer.


        :param id: The id of this Consumer.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Consumer.  # noqa: E501


        :return: The name of this Consumer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Consumer.


        :param name: The name of this Consumer.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def org_name(self):
        """Gets the org_name of this Consumer.  # noqa: E501


        :return: The org_name of this Consumer.  # noqa: E501
        :rtype: str
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name):
        """Sets the org_name of this Consumer.


        :param org_name: The org_name of this Consumer.  # noqa: E501
        :type: str
        """

        self._org_name = org_name

    @property
    def org_id(self):
        """Gets the org_id of this Consumer.  # noqa: E501


        :return: The org_id of this Consumer.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this Consumer.


        :param org_id: The org_id of this Consumer.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Consumer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Consumer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
