# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SubscriptionStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'overall_status': 'str',
        'products': 'list[ProductStatus]'
    }

    attribute_map = {
        'overall_status': 'overall_status',
        'products': 'products'
    }

    def __init__(self, overall_status=None, products=None):  # noqa: E501
        """SubscriptionStatus - a model defined in Swagger"""  # noqa: E501
        self._overall_status = None
        self._products = None
        self.discriminator = None
        if overall_status is not None:
            self.overall_status = overall_status
        if products is not None:
            self.products = products

    @property
    def overall_status(self):
        """Gets the overall_status of this SubscriptionStatus.  # noqa: E501


        :return: The overall_status of this SubscriptionStatus.  # noqa: E501
        :rtype: str
        """
        return self._overall_status

    @overall_status.setter
    def overall_status(self, overall_status):
        """Sets the overall_status of this SubscriptionStatus.


        :param overall_status: The overall_status of this SubscriptionStatus.  # noqa: E501
        :type: str
        """

        self._overall_status = overall_status

    @property
    def products(self):
        """Gets the products of this SubscriptionStatus.  # noqa: E501


        :return: The products of this SubscriptionStatus.  # noqa: E501
        :rtype: list[ProductStatus]
        """
        return self._products

    @products.setter
    def products(self, products):
        """Sets the products of this SubscriptionStatus.


        :param products: The products of this SubscriptionStatus.  # noqa: E501
        :type: list[ProductStatus]
        """

        self._products = products

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscriptionStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
