# coding: utf-8

"""
    candlepin-rpc-api

    RPC-ish interface for candlepin.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SystemPurpose(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role': 'str',
        'addons': 'list[str]',
        'usage': 'str',
        'sla': 'str'
    }

    attribute_map = {
        'role': 'role',
        'addons': 'addons',
        'usage': 'usage',
        'sla': 'sla'
    }

    def __init__(self, role=None, addons=None, usage=None, sla=None):  # noqa: E501
        """SystemPurpose - a model defined in Swagger"""  # noqa: E501
        self._role = None
        self._addons = None
        self._usage = None
        self._sla = None
        self.discriminator = None
        if role is not None:
            self.role = role
        if addons is not None:
            self.addons = addons
        if usage is not None:
            self.usage = usage
        if sla is not None:
            self.sla = sla

    @property
    def role(self):
        """Gets the role of this SystemPurpose.  # noqa: E501


        :return: The role of this SystemPurpose.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this SystemPurpose.


        :param role: The role of this SystemPurpose.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def addons(self):
        """Gets the addons of this SystemPurpose.  # noqa: E501


        :return: The addons of this SystemPurpose.  # noqa: E501
        :rtype: list[str]
        """
        return self._addons

    @addons.setter
    def addons(self, addons):
        """Sets the addons of this SystemPurpose.


        :param addons: The addons of this SystemPurpose.  # noqa: E501
        :type: list[str]
        """

        self._addons = addons

    @property
    def usage(self):
        """Gets the usage of this SystemPurpose.  # noqa: E501


        :return: The usage of this SystemPurpose.  # noqa: E501
        :rtype: str
        """
        return self._usage

    @usage.setter
    def usage(self, usage):
        """Sets the usage of this SystemPurpose.


        :param usage: The usage of this SystemPurpose.  # noqa: E501
        :type: str
        """

        self._usage = usage

    @property
    def sla(self):
        """Gets the sla of this SystemPurpose.  # noqa: E501


        :return: The sla of this SystemPurpose.  # noqa: E501
        :rtype: str
        """
        return self._sla

    @sla.setter
    def sla(self, sla):
        """Sets the sla of this SystemPurpose.


        :param sla: The sla of this SystemPurpose.  # noqa: E501
        :type: str
        """

        self._sla = sla

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemPurpose, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemPurpose):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
